# Generated by Django 3.2.8 on 2021-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('profile', models.IntegerField(choices=[(1, 'Admin'), (2, 'Anbieter'), (3, 'Suchender')], null=True, verbose_name='Profil')),
                ('agreed_on_terms', models.BooleanField(default=False, verbose_name='Datenschutzgenehmigung?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ist User aktiv?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Ist SuperUser?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Letztes Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Letztes Updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupo ao qual o usuário pertence. O usuário recebe todas as permissões dos grupos ao qual ele pertence.', related_name='user_groups', related_query_name='user', to='auth.Group', verbose_name='Grupos de usuário')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas do usuário.', related_name='user_permissions', related_query_name='user', to='auth.Permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzern',
            },
        ),
    ]
