# Generated by Django 3.1.10 on 2021-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foerderung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(choices=[('Baden-Wüttemberg', 'Baden-Wüttemberg'), ('Bayern', 'Bayern'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Niedersachsen', 'Niedersachsen'), ('Sachen-Anhalt', 'Sachen-Anhalt'), ('Hamburg', 'Hamburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Saarland', 'Saarland'), ('Sachsen', 'Sachsen'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thüringen', 'Thüringen')], default=None, max_length=80)),
                ('thema', models.CharField(choices=[('Arbeit', 'Arbeit'), ('Aus- & Weiterbildung', 'Aus- & Weiterbildung'), ('Corona-Hilfe', 'Corona-Hilfe'), ('Digitalisierung', 'Digitalisierung'), ('Energieeffizienz & Erneuerbare Energien', 'Energieeffizienz & Erneuerbare Energien'), ('Existenzgründung & -festigung', 'Existenzgründung & -festigung'), ('Forschung & Innovation (themenoffen)', 'Forschung & Innovation (themenoffen)'), ('Forschung & Innovation (themenspezifisch)', 'Forschung & Innovation (themenspezifisch)'), ('Gesundheit & Soziales', 'Gesundheit & Soziales'), ('Infrastruktur', 'Infrastruktur'), ('Kultur, Medien & Sport', 'Kultur, Medien & Sport'), ('Landwirtschaftlich & Ländliche Entwicklung', 'Landwirtschaftlich & Ländliche Entwicklung'), ('Regionalförderung', 'Regionalförderung'), ('Smart Cities & Regionen', 'Smart Cities & Regionen'), ('Städtebau & Stadterneuerung', 'Städtebau & Stadterneuerung'), ('Umwelt- & Naturschutz', 'Umwelt- & Naturschutz'), ('Unternehmensfinanzierung', 'Unternehmensfinanzierung'), ('Wohnungsbau & Modernisierung', 'Wohnungsbau & Modernisierung')], default=None, max_length=80)),
                ('unterkategorie', models.CharField(choices=[('Schulen', 'Schulen'), ('Sporteinrichtung', 'Sporteinrichtung'), ('Wasserwirtschaft', 'Wasserwirtschaft'), ('Abwasserwirtschaft', 'Abwasserwirtschaft'), ('Breitbandnetzte', 'Breitbandnetzte'), ('Verkehrsinfrastruktur', 'Verkehrsinfrastruktur'), ('Abfallwirtschaft', 'Abfallwirtschaft'), ('Stadtentwicklung', 'Stadtentwicklung'), ('Dorfentwicklung', 'Dorfentwicklung'), ('Tourismus', 'Tourismus'), ('Krankenhaus', 'Krankenhaus'), ('Behinderteneinrichtungen', 'Behinderteneinrichtungen'), ('Flüchtlingsunterkünfte', 'Flüchtlingsunterkünfte'), ('Baulanderschließung', 'Baulanderschließung'), ('Planungsleistung', 'Planungsleistung'), ('Grundstücke', 'Grundstücke')], default=None, max_length=80)),
                ('foerderprogramm', models.CharField(max_length=500)),
                ('foerdergeber', models.CharField(max_length=500)),
                ('foerderart', models.CharField(max_length=500)),
                ('foerderhoehe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nicht_foerderbare_ausgaben', models.CharField(max_length=500)),
                ('foerderprogramm_bezeichnung', models.CharField(max_length=500)),
                ('vorhabenbeginn', models.CharField(max_length=500)),
                ('rechtsgrundlage', models.CharField(max_length=500)),
                ('laufzeit', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
