# Generated by Django 3.1.10 on 2021-10-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foerderung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foerderung',
            old_name='states',
            new_name='foerdergebiet',
        ),
    ]
