# Generated by Django 3.1.10 on 2021-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foerderung', '0002_auto_20211027_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerderung',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foerderung',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='foerderung',
            name='foerdergebiet',
            field=models.CharField(choices=[('Baden-Würtemberg', 'Baden-Würtemberg'), ('Bayern', 'Bayern'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Niedersachsen', 'Niedersachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Hamburg', 'Hamburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Saarland', 'Saarland'), ('Sachsen', 'Sachsen'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thüringen', 'Thüringen')], default=None, max_length=80),
        ),
    ]
