# Generated by Django 3.1.10 on 2021-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foerderung', '0003_auto_20211028_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foerderung',
            name='nicht_foerderbare_ausgaben',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foerderung',
            name='vorhabenbeginn',
            field=models.DateField(),
        ),
    ]
