# Generated by Django 3.1.10 on 2021-10-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kriterienkatalog', '0001_initial'),
        ('foerderung', '0004_auto_20211028_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='foerderung',
            name='kriterienkatalog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kriterienkatalog.kriterienkatalog'),
        ),
    ]
