# Generated by Django 3.2.8 on 2021-11-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingprogramm',
            name='region',
            field=models.CharField(choices=[('Hessen', 'Hessen'), ('Baden Würtemberg', 'Baden Würtemberg'), ('Bayern', 'Bayern'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Brandenburg', 'Brandenburg'), ('Berlin', 'Berlin'), ('Bremen', 'Bremen'), ('Niedersachsen', 'Niedersachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Hamburg', 'Hamburg'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Sachsen', 'Sachsen'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Sonstige', 'Sonstige'), ('Thüringen', 'Thüringen'), ('Bundesweit', 'Bundesweit')], default='RP', max_length=64, verbose_name='Födergebiet'),
        ),
    ]
