# Generated by Django 3.2.8 on 2021-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_alter_fundingprogramm_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingprogramm',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Letzte bearbeitet'),
        ),
        migrations.AlterField(
            model_name='fundingprogramm',
            name='type',
            field=models.CharField(choices=[('Zuschuss', 'Zuschuss'), ('Kredit', 'Kredit'), ('Beteiligung', 'Beteiligung'), ('Bürgschaft', 'Bürgschaft'), ('Darlehen', 'Darlehen'), ('Garantie', 'Garantie'), ('sonstige', 'sonstige')], max_length=56, null=True, verbose_name='Förderungsart'),
        ),
    ]
