# Generated by Django 3.2.8 on 2021-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_auto_20211104_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('is_read', models.BooleanField(default=False, verbose_name='Ist die Nachricht schon gelesen?')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Ist die Nachricht schon geantworter?')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Zeit der Update')),
            ],
            options={
                'verbose_name': 'Kontakt Nachricht',
                'verbose_name_plural': 'Kontakt Nachrichten',
            },
        ),
    ]
