# Generated by Django 3.1.10 on 2021-10-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriterienkatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foerderprogramm_bezeichnung', models.CharField(max_length=500)),
                ('foerdergebiet', models.CharField(choices=[('Baden-Würtemberg', 'Baden-Würtemberg'), ('Bayern', 'Bayern'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Niedersachsen', 'Niedersachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Hamburg', 'Hamburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Saarland', 'Saarland'), ('Sachsen', 'Sachsen'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thüringen', 'Thüringen')], default=None, max_length=80)),
                ('foerdergeber', models.CharField(max_length=500)),
                ('foerderhoehe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foerderfaehige_kosten', models.DecimalField(decimal_places=0, max_digits=8)),
                ('nicht_foerderbare_ausgaben', models.CharField(max_length=500)),
                ('laufzeit', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
    ]
