# Generated by Django 3.1.10 on 2021-10-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriterienkatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kriterienkatalog',
            options={'verbose_name_plural': 'Kriterienkataloge'},
        ),
        migrations.RenameField(
            model_name='kriterienkatalog',
            old_name='foerderprogramm_bezeichnung',
            new_name='foerderprogramm',
        ),
    ]
